<?xml version="1.0" encoding="ISO-8859-1"?>
<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://ikno.ws/wsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://ikno.ws/wsdl">
<types>
<xsd:schema targetNamespace="http://ikno.ws/wsdl"
>
 <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/" />
 <xsd:import namespace="http://schemas.xmlsoap.org/wsdl/" />
</xsd:schema>
</types>
<message name="convertRequest">
  <part name="value" type="xsd:double" /></message>
<message name="convertResponse">
  <part name="return" type="xsd:double" /></message>
<portType name="mywsdlPortType">
  <operation name="convert">
    <documentation>converts feet to meters</documentation>
    <input message="tns:convertRequest"/>
    <output message="tns:convertResponse"/>
  </operation>
</portType>
<binding name="mywsdlBinding" type="tns:mywsdlPortType">
  <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
  <operation name="convert">
    <soap:operation soapAction="http://ikno.ws/wsdl#convert" style="rpc"/>
    <input><soap:body use="encoded" namespace="http://ikno.ws/wsdl" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></input>
    <output><soap:body use="encoded" namespace="http://ikno.ws/wsdl" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></output>
  </operation>
</binding>
<service name="mywsdl">
  <port name="mywsdlPort" binding="tns:mywsdlBinding">
    <soap:address location="http://ikno.ws/lab9/lserve.php"/>
  </port>
</service>
</definitions>